import type {Metadata} from "next";
import {Roboto, Roboto_Serif, Roboto_Mono} from "next/font/google";
import {Provider} from "@/components/ui/provider"
import "./globals.css";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/header";
import {Flex} from "@chakra-ui/react";
import React, {ReactNode} from "react";

const roboto = Roboto({
    variable: "--font-roboto",
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin', 'cyrillic'],
    display: 'swap',
});

const robotoSerif = Roboto_Serif({
    variable: "--font-roboto-serif",
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin', 'cyrillic'],
    display: 'swap',
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin', 'cyrillic'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="ru-RU" className={`${roboto.variable} ${robotoSerif.variable} ${robotoMono.variable}`}
              suppressHydrationWarning>
        <body>
        <Provider>
            <Header/>
            <Flex as="main" flex={1}>
                {children}
            </Flex>
            <Footer/>
        </Provider>
        </body>
        </html>
    );
}
